Module2 task1
htmlacademy-ecmascript/1296301-big-trip-14 pull request #4
Opened 2021-04-19 20:41 UTC by VioletNeon

2021-04-20 07:57 UTC, babtshe requested changes

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +const tripPoints = new Array(WAYPOINT_COUNT).fill(null).map(() => {return generatePoint();});
в случае со стрелочной функцией можно обойтись без явного return и лишних фигурных скобок.

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +};
количество точек маршрута ограничено уже при генерации. Тут вполне возможно пройти по массиву точек с помощью forEach.

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +renderAllWayPoints();
waypoint - одно слово, не нужно выделять в названии way**P**oint. При этом стоит привести остальные случаи использования к единообразию.

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +renderTemplate(tripEventsList, getEditingFormTemplate(tripPoints[0], destinations, offersPoint), 'afterbegin');
чтобы избавиться от магического значения, есть смысл положить значение по умолчанию в какую-то переменную с соответствующим названием и использовать уже её.

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +const getOfferTemplate = (typeOffers) => {
лучше не закидывать все шаблоны в main, а создавать отдельные файл для каждого компонента. В больших проектах это сильно упрощает навигацию.

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +  if (typeOffers.length > 0) {
стоит уточнить название переменной.

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +  if (description.length > 0 || destinationPictures.length > 0) {
если это массив, то было бы правильно назвать переменную существительным во множественном числе.

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +const checkDestinationNameTypes = (optionName, destination) => {
❗

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +typeGroup.addEventListener('change', callbackChangeOfferTemplate);
группа типов или тип группы?

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +const callbackClickNewPointButton = () => {
См [критерий](https://up.htmlacademy.ru/ecmascript/14/criteries#d4)

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +  typeGroup ? typeGroup.removeEventListener('change', callbackChangeOfferTemplate) : '';
здесь нет необходимости в тернарнике, простого if должно хватить.

2021-04-20 07:57 UTC, babtshe commented on src/main.js
> +  newPointButton.disabled = 'disabled';
обрати внимание на синтаксис возможных значений этого атрибута.

2021-04-20 07:57 UTC, babtshe commented on src/mock/point.js
> +};
стоит подумать как можно решить эту задачу более простым способом. Можно не исправлять, но подумать будет полезно.

2021-04-20 07:57 UTC, babtshe commented on src/mock/utils.js
> +  return array.sort(() => { return Math.random() - 0.5; }).slice(0, getRandomInteger(0, arrayLength));
не стоит использовать перемешивание массива через sort с костылями. Можно посмотреть в сторону алгоритма Фишера-Йетса.

2021-04-20 07:57 UTC, babtshe commented on src/view/trip-info.js
> +import {changeDateFormat, dayjs} from '../mock/utils.js';
утилиты есть смысл вытащить из папки с моками. Моки мы удалим, когда начнём работать с сервером, а утилиты могут пригодиться и потом.

2021-04-20 07:57 UTC, babtshe commented on src/view/trip-info.js
> +    if (offers.length > 0) {
для чего здесь нужна проверка длины массива?

2021-04-21 19:20 UTC, VioletNeon commented on src/view/trip-info.js
> +    if (offers.length > 0) {
Массив offers может быть пустым так как перед прогрузкой значений проходит через функцию getRandomInteger (рандомное перемешивание значений массива с формирование копии массива рандомной длины). Если массив пустой, то не проходит расчет цены с учетом цен дополнительных услуг.

2021-04-22 07:16 UTC, babtshe requested changes

2021-04-22 07:16 UTC, babtshe commented on src/main.js
>      }
судя по названию, функция должна вернуть дату, а на самом деле отдаёт объект с описанием и картинками.

2021-04-22 07:16 UTC, babtshe commented on src/main.js
> +  const creatingFormGroutType = document.querySelector('.event__type-group');
видимо опечатка

2021-04-22 07:16 UTC, babtshe commented on src/main.js
> +  newPointButton.disabled = 'disabled';
❗

2021-04-23 07:33 UTC, babtshe approved these changes

2021-04-23 07:33 UTC, merged